// Mirror of frontend mock data — used by the ticket agent when Jobber is not connected.

export const MOCK_CLIENTS = [
  { id: 'c01', name: 'Carmen Martinez' },
  { id: 'c02', name: 'Robert & Linda Thompson' },
  { id: 'c03', name: 'Wei Chen' },
  { id: 'c04', name: 'Priya Patel' },
  { id: 'c05', name: "Sean O'Brien" },
  { id: 'c06', name: 'Denise Williams' },
  { id: 'c07', name: 'Miguel Garcia' },
  { id: 'c08', name: 'Patricia Johnson' },
  { id: 'c09', name: 'Michael Anderson' },
  { id: 'c10', name: 'Thi Nguyen' },
  { id: 'c11', name: 'James Kim' },
  { id: 'c12', name: 'Sarah Brown' },
  { id: 'c13', name: 'Charles Davis' },
  { id: 'c14', name: 'Sunrise Villas HOA' },
  { id: 'c15', name: 'Coastal Property Mgmt' },
  { id: 'c16', name: 'Elena Rodriguez' },
  { id: 'c17', name: 'David White' },
  { id: 'c18', name: 'Jennifer Lee' },
  { id: 'c19', name: 'Marcus Taylor' },
  { id: 'c20', name: 'Blue Water Rentals LLC' },
  { id: 'c21', name: 'Martinez Properties' },
  { id: 'c22', name: 'Christine Cooper' },
  { id: 'c23', name: 'Thomas Walker' },
  { id: 'c24', name: 'Brenda Hall' },
  { id: 'c25', name: 'Emerald Coast Offices' },
];

export const MOCK_JOBS = [
  { id: 'j01', title: 'Weekly Residential Clean',   status: 'active',    client: { id: 'c01', name: 'Carmen Martinez' },         property: { street: '142 Magnolia Blvd',    city: 'Pensacola' } },
  { id: 'j02', title: 'Bi-Weekly Clean',            status: 'active',    client: { id: 'c01', name: 'Carmen Martinez' },         property: { street: '7 Palmetto Dr',         city: 'Gulf Breeze' } },
  { id: 'j03', title: 'Monthly Deep Clean',         status: 'active',    client: { id: 'c02', name: 'Robert & Linda Thompson' }, property: { street: '2310 Bayshore Ave',     city: 'Pensacola' } },
  { id: 'j04', title: 'Weekly Clean',               status: 'active',    client: { id: 'c03', name: 'Wei Chen' },                property: { street: '88 Crane Ct',           city: 'Navarre' } },
  { id: 'j05', title: 'Post-Construction Cleanup',  status: 'completed', client: { id: 'c03', name: 'Wei Chen' },                property: { street: '204 Sunrise Ln',        city: 'Navarre' } },
  { id: 'j06', title: 'Move-Out Deep Clean',        status: 'active',    client: { id: 'c04', name: 'Priya Patel' },            property: { street: '519 Oak Ridge Rd',      city: 'Milton' } },
  { id: 'j07', title: 'Vacation Rental Turnover',   status: 'active',    client: { id: 'c04', name: 'Priya Patel' },            property: { street: '33 Harbor View Dr',     city: 'Pensacola Beach' } },
  { id: 'j08', title: 'Bi-Weekly Residential',      status: 'active',    client: { id: 'c05', name: "Sean O'Brien" },           property: { street: '1045 Garden St',        city: 'Pensacola' } },
  { id: 'j09', title: 'Weekly Clean',               status: 'active',    client: { id: 'c06', name: 'Denise Williams' },        property: { street: '780 Westside Blvd',     city: 'Pace' } },
  { id: 'j10', title: 'Weekly Residential',         status: 'active',    client: { id: 'c08', name: 'Patricia Johnson' },       property: { street: '60 Sandpiper Rd',       city: 'Navarre' } },
  { id: 'j11', title: 'Move-In Clean',              status: 'completed', client: { id: 'c08', name: 'Patricia Johnson' },       property: { street: '120 Beachwood Cir',     city: 'Navarre' } },
  { id: 'j12', title: 'Bi-Weekly Clean',            status: 'active',    client: { id: 'c09', name: 'Michael Anderson' },       property: { street: '900 Nine Mile Rd',      city: 'Pensacola' } },
  { id: 'j13', title: 'Vacation Rental Turnover',   status: 'active',    client: { id: 'c09', name: 'Michael Anderson' },       property: { street: '47 Pier Park Way',      city: 'Panama City' } },
  { id: 'j14', title: 'Monthly Office Clean',       status: 'active',    client: { id: 'c10', name: 'Thi Nguyen' },             property: { street: '215 E Jackson St',      city: 'Pensacola' } },
  { id: 'j15', title: 'Weekly Residential',         status: 'active',    client: { id: 'c11', name: 'James Kim' },              property: { street: '441 Bauer Rd',          city: 'Milton' } },
  { id: 'j16', title: 'Vacation Rental Turnover',   status: 'active',    client: { id: 'c11', name: 'James Kim' },              property: { street: '18 Marina Blvd',        city: 'Pensacola Beach' } },
  { id: 'j17', title: 'Bi-Weekly Clean',            status: 'active',    client: { id: 'c12', name: 'Sarah Brown' },            property: { street: '700 Creekside Dr',      city: 'Pace' } },
  { id: 'j18', title: 'Weekly Clean',               status: 'active',    client: { id: 'c13', name: 'Charles Davis' },          property: { street: '1200 Cervantes St',     city: 'Pensacola' } },
  { id: 'j19', title: 'Monthly Deep Clean',         status: 'active',    client: { id: 'c13', name: 'Charles Davis' },          property: { street: '880 Scenic Hwy',        city: 'Pensacola' } },
  { id: 'j20', title: 'Clubhouse Weekly Clean',     status: 'active',    client: { id: 'c14', name: 'Sunrise Villas HOA' },     property: { street: '1 Sunrise Villas Clubhouse', city: 'Gulf Breeze' } },
  { id: 'j21', title: 'Pool Deck Bi-Weekly',        status: 'active',    client: { id: 'c14', name: 'Sunrise Villas HOA' },     property: { street: '2 Sunrise Villas Pool Deck', city: 'Gulf Breeze' } },
  { id: 'j22', title: 'Gym Daily Cleaning',         status: 'active',    client: { id: 'c14', name: 'Sunrise Villas HOA' },     property: { street: '3 Sunrise Villas Gym',       city: 'Gulf Breeze' } },
  { id: 'j23', title: 'Turnover Clean Unit A',      status: 'active',    client: { id: 'c15', name: 'Coastal Property Mgmt' }, property: { street: '410 Palafox St Unit A', city: 'Pensacola' } },
  { id: 'j24', title: 'Turnover Clean Unit B',      status: 'active',    client: { id: 'c15', name: 'Coastal Property Mgmt' }, property: { street: '410 Palafox St Unit B', city: 'Pensacola' } },
  { id: 'j25', title: 'Weekly Residential',         status: 'active',    client: { id: 'c16', name: 'Elena Rodriguez' },        property: { street: '2805 Tippin Ave',       city: 'Pensacola' } },
  { id: 'j26', title: 'Bi-Weekly Clean',            status: 'active',    client: { id: 'c17', name: 'David White' },            property: { street: '99 Whisper Pines Dr',   city: 'Milton' } },
  { id: 'j27', title: 'Monthly Deep Clean',         status: 'active',    client: { id: 'c18', name: 'Jennifer Lee' },           property: { street: '1700 E Moreno St',      city: 'Pensacola' } },
  { id: 'j28', title: 'Weekly Residential',         status: 'active',    client: { id: 'c19', name: 'Marcus Taylor' },          property: { street: '4520 Bayou Blvd',       city: 'Pensacola' } },
  { id: 'j29', title: 'Vacation Rental Turnover',   status: 'active',    client: { id: 'c19', name: 'Marcus Taylor' },          property: { street: '601 Scenic Gulf Dr',    city: 'Miramar Beach' } },
  { id: 'j30', title: 'Rental Turnover Unit 1',     status: 'active',    client: { id: 'c20', name: 'Blue Water Rentals LLC' }, property: { street: '12 Gulf Shore Dr Unit 1', city: 'Destin' } },
  { id: 'j31', title: 'Rental Turnover Unit 2',     status: 'active',    client: { id: 'c20', name: 'Blue Water Rentals LLC' }, property: { street: '12 Gulf Shore Dr Unit 2', city: 'Destin' } },
  { id: 'j32', title: 'Deep Clean Between Seasons', status: 'completed', client: { id: 'c20', name: 'Blue Water Rentals LLC' }, property: { street: '45 Harbor Cove Rd',     city: 'Destin' } },
  { id: 'j33', title: 'Monthly Rental Clean',       status: 'active',    client: { id: 'c21', name: 'Martinez Properties' },    property: { street: '890 W Fairfield Dr',    city: 'Pensacola' } },
  { id: 'j34', title: 'Bi-Weekly Residential',      status: 'active',    client: { id: 'c22', name: 'Christine Cooper' },       property: { street: '620 Aragon Ave',        city: 'Pensacola' } },
  { id: 'j35', title: 'Weekly Clean',               status: 'active',    client: { id: 'c23', name: 'Thomas Walker' },          property: { street: '3300 Barrancas Ave',    city: 'Pensacola' } },
  { id: 'j36', title: 'Seasonal Deep Clean',        status: 'completed', client: { id: 'c23', name: 'Thomas Walker' },          property: { street: '78 Quiet Cove Ln',      city: 'Gulf Breeze' } },
  { id: 'j37', title: 'Weekly Residential',         status: 'active',    client: { id: 'c24', name: 'Brenda Hall' },            property: { street: '505 E Gonzalez St',     city: 'Pensacola' } },
  { id: 'j38', title: 'Daily Office Clean Ste 100', status: 'active',    client: { id: 'c25', name: 'Emerald Coast Offices' },  property: { street: '2100 N Palafox St Ste 100', city: 'Pensacola' } },
  { id: 'j39', title: 'Daily Office Clean Ste 200', status: 'active',    client: { id: 'c25', name: 'Emerald Coast Offices' },  property: { street: '2100 N Palafox St Ste 200', city: 'Pensacola' } },
  { id: 'j40', title: 'Weekly Common Area Clean',   status: 'active',    client: { id: 'c25', name: 'Emerald Coast Offices' },  property: { street: '800 W Garden St Ste 300',   city: 'Pensacola' } },
];

const d = (offset: number) => {
  const dt = new Date();
  dt.setDate(dt.getDate() + offset);
  return dt.toISOString().slice(0, 10);
};

export const MOCK_VISITS = [
  { id: 'v01', title: 'Weekly Clean',              scheduledStart: d(1),  status: 'scheduled',   client: { id: 'c01', name: 'Carmen Martinez' },         property: { street: '142 Magnolia Blvd',    city: 'Pensacola' } },
  { id: 'v02', title: 'Bi-Weekly Clean',           scheduledStart: d(3),  status: 'scheduled',   client: { id: 'c01', name: 'Carmen Martinez' },         property: { street: '7 Palmetto Dr',         city: 'Gulf Breeze' } },
  { id: 'v03', title: 'Monthly Deep Clean',        scheduledStart: d(-2), status: 'completed',   client: { id: 'c02', name: 'Robert & Linda Thompson' }, property: { street: '2310 Bayshore Ave',     city: 'Pensacola' } },
  { id: 'v04', title: 'Weekly Clean',              scheduledStart: d(2),  status: 'scheduled',   client: { id: 'c03', name: 'Wei Chen' },                property: { street: '88 Crane Ct',           city: 'Navarre' } },
  { id: 'v07', title: 'Move-Out Deep Clean',       scheduledStart: d(0),  status: 'scheduled',   client: { id: 'c04', name: 'Priya Patel' },            property: { street: '519 Oak Ridge Rd',      city: 'Milton' } },
  { id: 'v08', title: 'Turnover Clean',            scheduledStart: d(1),  status: 'scheduled',   client: { id: 'c04', name: 'Priya Patel' },            property: { street: '33 Harbor View Dr',     city: 'Pensacola Beach' } },
  { id: 'v09', title: 'Bi-Weekly Residential',     scheduledStart: d(4),  status: 'scheduled',   client: { id: 'c05', name: "Sean O'Brien" },           property: { street: '1045 Garden St',        city: 'Pensacola' } },
  { id: 'v10', title: 'Weekly Clean',              scheduledStart: d(2),  status: 'scheduled',   client: { id: 'c06', name: 'Denise Williams' },        property: { street: '780 Westside Blvd',     city: 'Pace' } },
  { id: 'v13', title: 'Weekly Residential',        scheduledStart: d(3),  status: 'scheduled',   client: { id: 'c08', name: 'Patricia Johnson' },       property: { street: '60 Sandpiper Rd',       city: 'Navarre' } },
  { id: 'v16', title: 'Bi-Weekly Clean',           scheduledStart: d(5),  status: 'scheduled',   client: { id: 'c09', name: 'Michael Anderson' },       property: { street: '900 Nine Mile Rd',      city: 'Pensacola' } },
  { id: 'v17', title: 'Turnover Clean',            scheduledStart: d(1),  status: 'scheduled',   client: { id: 'c09', name: 'Michael Anderson' },       property: { street: '47 Pier Park Way',      city: 'Panama City' } },
  { id: 'v18', title: 'Monthly Office Clean',      scheduledStart: d(6),  status: 'scheduled',   client: { id: 'c10', name: 'Thi Nguyen' },             property: { street: '215 E Jackson St',      city: 'Pensacola' } },
  { id: 'v19', title: 'Weekly Residential',        scheduledStart: d(2),  status: 'scheduled',   client: { id: 'c11', name: 'James Kim' },              property: { street: '441 Bauer Rd',          city: 'Milton' } },
  { id: 'v20', title: 'Turnover Clean',            scheduledStart: d(0),  status: 'scheduled',   client: { id: 'c11', name: 'James Kim' },              property: { street: '18 Marina Blvd',        city: 'Pensacola Beach' } },
  { id: 'v25', title: 'Clubhouse Weekly',          scheduledStart: d(2),  status: 'scheduled',   client: { id: 'c14', name: 'Sunrise Villas HOA' },     property: { street: '1 Sunrise Villas Clubhouse', city: 'Gulf Breeze' } },
  { id: 'v26', title: 'Pool Deck Clean',           scheduledStart: d(4),  status: 'scheduled',   client: { id: 'c14', name: 'Sunrise Villas HOA' },     property: { street: '2 Sunrise Villas Pool Deck', city: 'Gulf Breeze' } },
  { id: 'v37', title: 'Turnover Unit 1',           scheduledStart: d(0),  status: 'scheduled',   client: { id: 'c20', name: 'Blue Water Rentals LLC' }, property: { street: '12 Gulf Shore Dr Unit 1', city: 'Destin' } },
  { id: 'v38', title: 'Turnover Unit 2',           scheduledStart: d(0),  status: 'scheduled',   client: { id: 'c20', name: 'Blue Water Rentals LLC' }, property: { street: '12 Gulf Shore Dr Unit 2', city: 'Destin' } },
  { id: 'v46', title: 'Daily Office Clean Ste 100',scheduledStart: d(1),  status: 'scheduled',   client: { id: 'c25', name: 'Emerald Coast Offices' },  property: { street: '2100 N Palafox St Ste 100', city: 'Pensacola' } },
  { id: 'v47', title: 'Daily Office Clean Ste 200',scheduledStart: d(1),  status: 'scheduled',   client: { id: 'c25', name: 'Emerald Coast Offices' },  property: { street: '2100 N Palafox St Ste 200', city: 'Pensacola' } },
];
