// Mirror of frontend mock data — used by the ticket agent when Jobber is not connected.

export const MOCK_VENDORS = [
  { id: 'vd01', name: 'Maria Santos',             email: 'maria.santos@cleanpro.com',    phone: '(850) 555-0201', specialty: 'Residential' },
  { id: 'vd02', name: 'Gulf Coast Cleaners LLC',  email: 'info@gulfcoastclean.com',      phone: '(850) 555-0202', specialty: 'Residential & Commercial' },
  { id: 'vd03', name: 'Sunshine Pro Clean',       email: 'ops@sunshinepro.com',           phone: '(850) 555-0203', specialty: 'Vacation Rentals' },
  { id: 'vd04', name: 'Emerald Clean Services',   email: 'contact@emeraldclean.com',      phone: '(850) 555-0204', specialty: 'HOA & Commercial' },
  { id: 'vd05', name: 'Bay Clean Team',           email: 'bay@baycleanteam.com',          phone: '(850) 555-0205', specialty: 'Commercial & Turnover' },
  { id: 'vd06', name: 'Coastal Pro Clean',        email: 'hello@coastalpro.com',          phone: '(850) 555-0206', specialty: 'General Residential' },
  { id: 'vd07', name: 'Pristine Clean Co.',       email: 'admin@pristineclean.com',       phone: '(850) 555-0207', specialty: 'Deep Clean Specialist' },
  { id: 'vd08', name: 'Gulf Breeze Services',     email: 'info@gulfbreezesvcs.com',       phone: '(850) 555-0208', specialty: 'Vacation Rentals & Deep Clean' },
];

const V = (id: string, name: string) => ({ id, name });

export const MOCK_CLIENTS = [
  { id: 'c01', name: 'Carmen Martinez' },
  { id: 'c02', name: 'Robert & Linda Thompson' },
  { id: 'c03', name: 'Wei Chen' },
  { id: 'c04', name: 'Priya Patel' },
  { id: 'c05', name: "Sean O'Brien" },
  { id: 'c06', name: 'Denise Williams' },
  { id: 'c07', name: 'Miguel Garcia' },
  { id: 'c08', name: 'Patricia Johnson' },
  { id: 'c09', name: 'Michael Anderson' },
  { id: 'c10', name: 'Thi Nguyen' },
  { id: 'c11', name: 'James Kim' },
  { id: 'c12', name: 'Sarah Brown' },
  { id: 'c13', name: 'Charles Davis' },
  { id: 'c14', name: 'Sunrise Villas HOA' },
  { id: 'c15', name: 'Coastal Property Mgmt' },
  { id: 'c16', name: 'Elena Rodriguez' },
  { id: 'c17', name: 'David White' },
  { id: 'c18', name: 'Jennifer Lee' },
  { id: 'c19', name: 'Marcus Taylor' },
  { id: 'c20', name: 'Blue Water Rentals LLC' },
  { id: 'c21', name: 'Martinez Properties' },
  { id: 'c22', name: 'Christine Cooper' },
  { id: 'c23', name: 'Thomas Walker' },
  { id: 'c24', name: 'Brenda Hall' },
  { id: 'c25', name: 'Emerald Coast Offices' },
];

export const MOCK_JOBS = [
  { id: 'j01', title: 'Weekly Residential Clean',   status: 'active',    client: { id: 'c01', name: 'Carmen Martinez' },         property: { street: '142 Magnolia Blvd',    city: 'Pensacola' },      vendor: V('vd01','Maria Santos') },
  { id: 'j02', title: 'Bi-Weekly Clean',            status: 'active',    client: { id: 'c01', name: 'Carmen Martinez' },         property: { street: '7 Palmetto Dr',         city: 'Gulf Breeze' },    vendor: V('vd02','Gulf Coast Cleaners LLC') },
  { id: 'j03', title: 'Monthly Deep Clean',         status: 'active',    client: { id: 'c02', name: 'Robert & Linda Thompson' }, property: { street: '2310 Bayshore Ave',     city: 'Pensacola' },      vendor: V('vd02','Gulf Coast Cleaners LLC') },
  { id: 'j04', title: 'Weekly Clean',               status: 'active',    client: { id: 'c03', name: 'Wei Chen' },                property: { street: '88 Crane Ct',           city: 'Navarre' },        vendor: V('vd01','Maria Santos') },
  { id: 'j05', title: 'Post-Construction Cleanup',  status: 'completed', client: { id: 'c03', name: 'Wei Chen' },                property: { street: '204 Sunrise Ln',        city: 'Navarre' },        vendor: V('vd08','Gulf Breeze Services') },
  { id: 'j06', title: 'Move-Out Deep Clean',        status: 'active',    client: { id: 'c04', name: 'Priya Patel' },            property: { street: '519 Oak Ridge Rd',      city: 'Milton' },         vendor: V('vd03','Sunshine Pro Clean') },
  { id: 'j07', title: 'Vacation Rental Turnover',   status: 'active',    client: { id: 'c04', name: 'Priya Patel' },            property: { street: '33 Harbor View Dr',     city: 'Pensacola Beach' }, vendor: V('vd03','Sunshine Pro Clean') },
  { id: 'j08', title: 'Bi-Weekly Residential',      status: 'active',    client: { id: 'c05', name: "Sean O'Brien" },           property: { street: '1045 Garden St',        city: 'Pensacola' },      vendor: V('vd02','Gulf Coast Cleaners LLC') },
  { id: 'j09', title: 'Weekly Clean',               status: 'active',    client: { id: 'c06', name: 'Denise Williams' },        property: { street: '780 Westside Blvd',     city: 'Pace' },           vendor: V('vd04','Emerald Clean Services') },
  { id: 'j10', title: 'Weekly Residential',         status: 'active',    client: { id: 'c08', name: 'Patricia Johnson' },       property: { street: '60 Sandpiper Rd',       city: 'Navarre' },        vendor: V('vd01','Maria Santos') },
  { id: 'j11', title: 'Move-In Clean',              status: 'active',    client: { id: 'c08', name: 'Patricia Johnson' },       property: { street: '120 Beachwood Cir',     city: 'Navarre' },        vendor: V('vd01','Maria Santos') },
  { id: 'j12', title: 'Bi-Weekly Clean',            status: 'active',    client: { id: 'c09', name: 'Michael Anderson' },       property: { street: '900 Nine Mile Rd',      city: 'Pensacola' },      vendor: V('vd05','Bay Clean Team') },
  { id: 'j13', title: 'Vacation Rental Turnover',   status: 'active',    client: { id: 'c09', name: 'Michael Anderson' },       property: { street: '47 Pier Park Way',      city: 'Panama City' },    vendor: V('vd05','Bay Clean Team') },
  { id: 'j14', title: 'Monthly Office Clean',       status: 'active',    client: { id: 'c10', name: 'Thi Nguyen' },             property: { street: '215 E Jackson St',      city: 'Pensacola' },      vendor: V('vd06','Coastal Pro Clean') },
  { id: 'j15', title: 'Weekly Residential',         status: 'active',    client: { id: 'c11', name: 'James Kim' },              property: { street: '441 Bauer Rd',          city: 'Milton' },         vendor: V('vd03','Sunshine Pro Clean') },
  { id: 'j16', title: 'Vacation Rental Turnover',   status: 'active',    client: { id: 'c11', name: 'James Kim' },              property: { street: '18 Marina Blvd',        city: 'Pensacola Beach' }, vendor: V('vd03','Sunshine Pro Clean') },
  { id: 'j17', title: 'Bi-Weekly Clean',            status: 'active',    client: { id: 'c12', name: 'Sarah Brown' },            property: { street: '700 Creekside Dr',      city: 'Pace' },           vendor: V('vd02','Gulf Coast Cleaners LLC') },
  { id: 'j18', title: 'Weekly Clean',               status: 'active',    client: { id: 'c13', name: 'Charles Davis' },          property: { street: '1200 Cervantes St',     city: 'Pensacola' },      vendor: V('vd07','Pristine Clean Co.') },
  { id: 'j19', title: 'Monthly Deep Clean',         status: 'active',    client: { id: 'c13', name: 'Charles Davis' },          property: { street: '880 Scenic Hwy',        city: 'Pensacola' },      vendor: V('vd07','Pristine Clean Co.') },
  { id: 'j20', title: 'Clubhouse Weekly Clean',     status: 'active',    client: { id: 'c14', name: 'Sunrise Villas HOA' },     property: { street: '1 Sunrise Villas Clubhouse', city: 'Gulf Breeze' }, vendor: V('vd04','Emerald Clean Services') },
  { id: 'j21', title: 'Pool Deck Bi-Weekly',        status: 'active',    client: { id: 'c14', name: 'Sunrise Villas HOA' },     property: { street: '2 Sunrise Villas Pool Deck', city: 'Gulf Breeze' }, vendor: V('vd04','Emerald Clean Services') },
  { id: 'j22', title: 'Gym Daily Cleaning',         status: 'active',    client: { id: 'c14', name: 'Sunrise Villas HOA' },     property: { street: '3 Sunrise Villas Gym',       city: 'Gulf Breeze' }, vendor: V('vd04','Emerald Clean Services') },
  { id: 'j23', title: 'Turnover Clean Unit A',      status: 'active',    client: { id: 'c15', name: 'Coastal Property Mgmt' }, property: { street: '410 Palafox St Unit A', city: 'Pensacola' },  vendor: V('vd05','Bay Clean Team') },
  { id: 'j24', title: 'Turnover Clean Unit B',      status: 'active',    client: { id: 'c15', name: 'Coastal Property Mgmt' }, property: { street: '410 Palafox St Unit B', city: 'Pensacola' },  vendor: V('vd05','Bay Clean Team') },
  { id: 'j25', title: 'Weekly Residential',         status: 'active',    client: { id: 'c16', name: 'Elena Rodriguez' },        property: { street: '2805 Tippin Ave',       city: 'Pensacola' },      vendor: V('vd01','Maria Santos') },
  { id: 'j26', title: 'Bi-Weekly Clean',            status: 'active',    client: { id: 'c17', name: 'David White' },            property: { street: '99 Whisper Pines Dr',   city: 'Milton' },         vendor: V('vd06','Coastal Pro Clean') },
  { id: 'j27', title: 'Monthly Deep Clean',         status: 'active',    client: { id: 'c18', name: 'Jennifer Lee' },           property: { street: '1700 E Moreno St',      city: 'Pensacola' },      vendor: V('vd07','Pristine Clean Co.') },
  { id: 'j28', title: 'Weekly Residential',         status: 'active',    client: { id: 'c19', name: 'Marcus Taylor' },          property: { street: '4520 Bayou Blvd',       city: 'Pensacola' },      vendor: V('vd03','Sunshine Pro Clean') },
  { id: 'j29', title: 'Vacation Rental Turnover',   status: 'active',    client: { id: 'c19', name: 'Marcus Taylor' },          property: { street: '601 Scenic Gulf Dr',    city: 'Miramar Beach' },  vendor: V('vd03','Sunshine Pro Clean') },
  { id: 'j30', title: 'Rental Turnover Unit 1',     status: 'active',    client: { id: 'c20', name: 'Blue Water Rentals LLC' }, property: { street: '12 Gulf Shore Dr Unit 1', city: 'Destin' },    vendor: V('vd08','Gulf Breeze Services') },
  { id: 'j31', title: 'Rental Turnover Unit 2',     status: 'active',    client: { id: 'c20', name: 'Blue Water Rentals LLC' }, property: { street: '12 Gulf Shore Dr Unit 2', city: 'Destin' },    vendor: V('vd08','Gulf Breeze Services') },
  { id: 'j32', title: 'Deep Clean Between Seasons', status: 'completed', client: { id: 'c20', name: 'Blue Water Rentals LLC' }, property: { street: '45 Harbor Cove Rd',     city: 'Destin' },         vendor: V('vd08','Gulf Breeze Services') },
  { id: 'j33', title: 'Monthly Rental Clean',       status: 'active',    client: { id: 'c21', name: 'Martinez Properties' },    property: { street: '890 W Fairfield Dr',    city: 'Pensacola' },      vendor: V('vd02','Gulf Coast Cleaners LLC') },
  { id: 'j34', title: 'Bi-Weekly Residential',      status: 'active',    client: { id: 'c22', name: 'Christine Cooper' },       property: { street: '620 Aragon Ave',        city: 'Pensacola' },      vendor: V('vd04','Emerald Clean Services') },
  { id: 'j35', title: 'Weekly Clean',               status: 'active',    client: { id: 'c23', name: 'Thomas Walker' },          property: { street: '3300 Barrancas Ave',    city: 'Pensacola' },      vendor: V('vd06','Coastal Pro Clean') },
  { id: 'j36', title: 'Seasonal Deep Clean',        status: 'completed', client: { id: 'c23', name: 'Thomas Walker' },          property: { street: '78 Quiet Cove Ln',      city: 'Gulf Breeze' },    vendor: V('vd06','Coastal Pro Clean') },
  { id: 'j37', title: 'Weekly Residential',         status: 'active',    client: { id: 'c24', name: 'Brenda Hall' },            property: { street: '505 E Gonzalez St',     city: 'Pensacola' },      vendor: V('vd07','Pristine Clean Co.') },
  { id: 'j38', title: 'Daily Office Clean Ste 100', status: 'active',    client: { id: 'c25', name: 'Emerald Coast Offices' },  property: { street: '2100 N Palafox St Ste 100', city: 'Pensacola' }, vendor: V('vd05','Bay Clean Team') },
  { id: 'j39', title: 'Daily Office Clean Ste 200', status: 'active',    client: { id: 'c25', name: 'Emerald Coast Offices' },  property: { street: '2100 N Palafox St Ste 200', city: 'Pensacola' }, vendor: V('vd05','Bay Clean Team') },
  { id: 'j40', title: 'Weekly Common Area Clean',   status: 'active',    client: { id: 'c25', name: 'Emerald Coast Offices' },  property: { street: '800 W Garden St Ste 300',   city: 'Pensacola' }, vendor: V('vd05','Bay Clean Team') },
];

const d = (offset: number) => {
  const dt = new Date();
  dt.setDate(dt.getDate() + offset);
  return dt.toISOString().slice(0, 10);
};

export const MOCK_VISITS = [
  { id: 'v01', title: 'Weekly Clean',              scheduledStart: d(1),   status: 'scheduled',   client: { id: 'c01', name: 'Carmen Martinez' },         property: { street: '142 Magnolia Blvd',         city: 'Pensacola' },       vendor: V('vd01','Maria Santos') },
  { id: 'v02', title: 'Bi-Weekly Clean',           scheduledStart: d(3),   status: 'scheduled',   client: { id: 'c01', name: 'Carmen Martinez' },         property: { street: '7 Palmetto Dr',              city: 'Gulf Breeze' },     vendor: V('vd02','Gulf Coast Cleaners LLC') },
  { id: 'v03', title: 'Monthly Deep Clean',        scheduledStart: d(-2),  status: 'completed',   client: { id: 'c02', name: 'Robert & Linda Thompson' }, property: { street: '2310 Bayshore Ave',          city: 'Pensacola' },       vendor: V('vd02','Gulf Coast Cleaners LLC') },
  { id: 'v04', title: 'Weekly Clean',              scheduledStart: d(2),   status: 'scheduled',   client: { id: 'c03', name: 'Wei Chen' },                property: { street: '88 Crane Ct',               city: 'Navarre' },         vendor: V('vd01','Maria Santos') },
  { id: 'v05', title: 'Post-Construction Visit',   scheduledStart: d(-5),  status: 'completed',   client: { id: 'c03', name: 'Wei Chen' },                property: { street: '204 Sunrise Ln',            city: 'Navarre' },         vendor: V('vd08','Gulf Breeze Services') },
  { id: 'v06', title: 'Initial Walk-Through',      scheduledStart: d(7),   status: 'scheduled',   client: { id: 'c03', name: 'Wei Chen' },                property: { street: '11 Pelican Pl',             city: 'Gulf Breeze' },     vendor: V('vd01','Maria Santos') },
  { id: 'v07', title: 'Move-Out Deep Clean',       scheduledStart: d(0),   status: 'scheduled',   client: { id: 'c04', name: 'Priya Patel' },            property: { street: '519 Oak Ridge Rd',          city: 'Milton' },          vendor: V('vd03','Sunshine Pro Clean') },
  { id: 'v08', title: 'Turnover Clean',            scheduledStart: d(1),   status: 'scheduled',   client: { id: 'c04', name: 'Priya Patel' },            property: { street: '33 Harbor View Dr',         city: 'Pensacola Beach' },  vendor: V('vd03','Sunshine Pro Clean') },
  { id: 'v09', title: 'Bi-Weekly Residential',     scheduledStart: d(4),   status: 'scheduled',   client: { id: 'c05', name: "Sean O'Brien" },           property: { street: '1045 Garden St',            city: 'Pensacola' },       vendor: V('vd02','Gulf Coast Cleaners LLC') },
  { id: 'v10', title: 'Weekly Clean',              scheduledStart: d(2),   status: 'scheduled',   client: { id: 'c06', name: 'Denise Williams' },        property: { street: '780 Westside Blvd',         city: 'Pace' },            vendor: V('vd04','Emerald Clean Services') },
  { id: 'v11', title: 'Initial Assessment',        scheduledStart: d(10),  status: 'unscheduled', client: { id: 'c06', name: 'Denise Williams' },        property: { street: '22 Coral Way',              city: 'Gulf Breeze' },     vendor: V('vd04','Emerald Clean Services') },
  { id: 'v12', title: 'One-Time Deep Clean',       scheduledStart: d(-1),  status: 'completed',   client: { id: 'c07', name: 'Miguel Garcia' },          property: { street: '3301 Davis Hwy',            city: 'Pensacola' },       vendor: V('vd08','Gulf Breeze Services') },
  { id: 'v13', title: 'Weekly Residential',        scheduledStart: d(3),   status: 'scheduled',   client: { id: 'c08', name: 'Patricia Johnson' },       property: { street: '60 Sandpiper Rd',           city: 'Navarre' },         vendor: V('vd01','Maria Santos') },
  { id: 'v14', title: 'Move-In Clean',             scheduledStart: d(5),   status: 'scheduled',   client: { id: 'c08', name: 'Patricia Johnson' },       property: { street: '120 Beachwood Cir',         city: 'Navarre' },         vendor: V('vd01','Maria Santos') },
  { id: 'v15', title: 'One-Time Clean',            scheduledStart: d(14),  status: 'unscheduled', client: { id: 'c08', name: 'Patricia Johnson' },       property: { street: '5 Inlet Pointe Dr',         city: 'Pensacola' },       vendor: V('vd01','Maria Santos') },
  { id: 'v16', title: 'Bi-Weekly Clean',           scheduledStart: d(5),   status: 'scheduled',   client: { id: 'c09', name: 'Michael Anderson' },       property: { street: '900 Nine Mile Rd',          city: 'Pensacola' },       vendor: V('vd05','Bay Clean Team') },
  { id: 'v17', title: 'Turnover Clean',            scheduledStart: d(1),   status: 'scheduled',   client: { id: 'c09', name: 'Michael Anderson' },       property: { street: '47 Pier Park Way',          city: 'Panama City' },     vendor: V('vd05','Bay Clean Team') },
  { id: 'v18', title: 'Monthly Office Clean',      scheduledStart: d(6),   status: 'scheduled',   client: { id: 'c10', name: 'Thi Nguyen' },             property: { street: '215 E Jackson St',          city: 'Pensacola' },       vendor: V('vd06','Coastal Pro Clean') },
  { id: 'v19', title: 'Weekly Residential',        scheduledStart: d(2),   status: 'scheduled',   client: { id: 'c11', name: 'James Kim' },              property: { street: '441 Bauer Rd',              city: 'Milton' },          vendor: V('vd03','Sunshine Pro Clean') },
  { id: 'v20', title: 'Turnover Clean',            scheduledStart: d(0),   status: 'scheduled',   client: { id: 'c11', name: 'James Kim' },              property: { street: '18 Marina Blvd',            city: 'Pensacola Beach' },  vendor: V('vd03','Sunshine Pro Clean') },
  { id: 'v21', title: 'Bi-Weekly Clean',           scheduledStart: d(4),   status: 'scheduled',   client: { id: 'c12', name: 'Sarah Brown' },            property: { street: '700 Creekside Dr',          city: 'Pace' },            vendor: V('vd02','Gulf Coast Cleaners LLC') },
  { id: 'v22', title: 'Weekly Clean',              scheduledStart: d(1),   status: 'scheduled',   client: { id: 'c13', name: 'Charles Davis' },          property: { street: '1200 Cervantes St',         city: 'Pensacola' },       vendor: V('vd07','Pristine Clean Co.') },
  { id: 'v23', title: 'Estimate Visit',            scheduledStart: d(9),   status: 'unscheduled', client: { id: 'c13', name: 'Charles Davis' },          property: { street: '34 Osprey Way',             city: 'Gulf Breeze' },     vendor: V('vd07','Pristine Clean Co.') },
  { id: 'v24', title: 'Monthly Deep Clean',        scheduledStart: d(-1),  status: 'completed',   client: { id: 'c13', name: 'Charles Davis' },          property: { street: '880 Scenic Hwy',            city: 'Pensacola' },       vendor: V('vd07','Pristine Clean Co.') },
  { id: 'v25', title: 'Clubhouse Weekly',          scheduledStart: d(2),   status: 'scheduled',   client: { id: 'c14', name: 'Sunrise Villas HOA' },     property: { street: '1 Sunrise Villas Clubhouse', city: 'Gulf Breeze' },    vendor: V('vd04','Emerald Clean Services') },
  { id: 'v26', title: 'Pool Deck Clean',           scheduledStart: d(4),   status: 'scheduled',   client: { id: 'c14', name: 'Sunrise Villas HOA' },     property: { street: '2 Sunrise Villas Pool Deck', city: 'Gulf Breeze' },    vendor: V('vd04','Emerald Clean Services') },
  { id: 'v27', title: 'Gym Daily Clean',           scheduledStart: d(1),   status: 'scheduled',   client: { id: 'c14', name: 'Sunrise Villas HOA' },     property: { street: '3 Sunrise Villas Gym',      city: 'Gulf Breeze' },    vendor: V('vd04','Emerald Clean Services') },
  { id: 'v28', title: 'Turnover Unit A',           scheduledStart: d(3),   status: 'scheduled',   client: { id: 'c15', name: 'Coastal Property Mgmt' }, property: { street: '410 Palafox St Unit A',     city: 'Pensacola' },       vendor: V('vd05','Bay Clean Team') },
  { id: 'v29', title: 'Turnover Unit B',           scheduledStart: d(5),   status: 'scheduled',   client: { id: 'c15', name: 'Coastal Property Mgmt' }, property: { street: '410 Palafox St Unit B',     city: 'Pensacola' },       vendor: V('vd05','Bay Clean Team') },
  { id: 'v30', title: 'Initial Walkthrough',       scheduledStart: d(12),  status: 'unscheduled', client: { id: 'c15', name: 'Coastal Property Mgmt' }, property: { street: '55 Bayfront Pkwy',          city: 'Pensacola' },       vendor: V('vd05','Bay Clean Team') },
  { id: 'v31', title: 'Weekly Residential',        scheduledStart: d(2),   status: 'scheduled',   client: { id: 'c16', name: 'Elena Rodriguez' },        property: { street: '2805 Tippin Ave',           city: 'Pensacola' },       vendor: V('vd01','Maria Santos') },
  { id: 'v32', title: 'Bi-Weekly Clean',           scheduledStart: d(6),   status: 'scheduled',   client: { id: 'c17', name: 'David White' },            property: { street: '99 Whisper Pines Dr',       city: 'Milton' },          vendor: V('vd06','Coastal Pro Clean') },
  { id: 'v33', title: 'One-Time Deep Clean',       scheduledStart: d(21),  status: 'unscheduled', client: { id: 'c17', name: 'David White' },            property: { street: '310 Avalon Blvd',           city: 'Milton' },          vendor: V('vd06','Coastal Pro Clean') },
  { id: 'v34', title: 'Monthly Deep Clean',        scheduledStart: d(8),   status: 'scheduled',   client: { id: 'c18', name: 'Jennifer Lee' },           property: { street: '1700 E Moreno St',          city: 'Pensacola' },       vendor: V('vd07','Pristine Clean Co.') },
  { id: 'v35', title: 'Weekly Residential',        scheduledStart: d(1),   status: 'scheduled',   client: { id: 'c19', name: 'Marcus Taylor' },          property: { street: '4520 Bayou Blvd',           city: 'Pensacola' },       vendor: V('vd03','Sunshine Pro Clean') },
  { id: 'v36', title: 'Turnover Clean',            scheduledStart: d(2),   status: 'scheduled',   client: { id: 'c19', name: 'Marcus Taylor' },          property: { street: '601 Scenic Gulf Dr',        city: 'Miramar Beach' },   vendor: V('vd03','Sunshine Pro Clean') },
  { id: 'v37', title: 'Turnover Unit 1',           scheduledStart: d(0),   status: 'scheduled',   client: { id: 'c20', name: 'Blue Water Rentals LLC' }, property: { street: '12 Gulf Shore Dr Unit 1',   city: 'Destin' },          vendor: V('vd08','Gulf Breeze Services') },
  { id: 'v38', title: 'Turnover Unit 2',           scheduledStart: d(0),   status: 'scheduled',   client: { id: 'c20', name: 'Blue Water Rentals LLC' }, property: { street: '12 Gulf Shore Dr Unit 2',   city: 'Destin' },          vendor: V('vd08','Gulf Breeze Services') },
  { id: 'v39', title: 'Deep Clean Harbor Cove',    scheduledStart: d(-7),  status: 'completed',   client: { id: 'c20', name: 'Blue Water Rentals LLC' }, property: { street: '45 Harbor Cove Rd',         city: 'Destin' },          vendor: V('vd08','Gulf Breeze Services') },
  { id: 'v40', title: 'Monthly Rental Clean',      scheduledStart: d(5),   status: 'scheduled',   client: { id: 'c21', name: 'Martinez Properties' },    property: { street: '890 W Fairfield Dr',        city: 'Pensacola' },       vendor: V('vd02','Gulf Coast Cleaners LLC') },
  { id: 'v41', title: 'Estimate Visit',            scheduledStart: d(15),  status: 'unscheduled', client: { id: 'c21', name: 'Martinez Properties' },    property: { street: '1100 N Davis Hwy',          city: 'Pensacola' },       vendor: V('vd02','Gulf Coast Cleaners LLC') },
  { id: 'v42', title: 'Bi-Weekly Residential',     scheduledStart: d(3),   status: 'scheduled',   client: { id: 'c22', name: 'Christine Cooper' },       property: { street: '620 Aragon Ave',            city: 'Pensacola' },       vendor: V('vd04','Emerald Clean Services') },
  { id: 'v43', title: 'Weekly Clean',              scheduledStart: d(1),   status: 'scheduled',   client: { id: 'c23', name: 'Thomas Walker' },          property: { street: '3300 Barrancas Ave',        city: 'Pensacola' },       vendor: V('vd06','Coastal Pro Clean') },
  { id: 'v44', title: 'Seasonal Deep Clean',       scheduledStart: d(-4),  status: 'completed',   client: { id: 'c23', name: 'Thomas Walker' },          property: { street: '78 Quiet Cove Ln',          city: 'Gulf Breeze' },     vendor: V('vd06','Coastal Pro Clean') },
  { id: 'v45', title: 'Weekly Residential',        scheduledStart: d(2),   status: 'scheduled',   client: { id: 'c24', name: 'Brenda Hall' },            property: { street: '505 E Gonzalez St',         city: 'Pensacola' },       vendor: V('vd07','Pristine Clean Co.') },
  { id: 'v46', title: 'Daily Office Clean Ste 100',scheduledStart: d(1),   status: 'scheduled',   client: { id: 'c25', name: 'Emerald Coast Offices' },  property: { street: '2100 N Palafox St Ste 100', city: 'Pensacola' },       vendor: V('vd05','Bay Clean Team') },
  { id: 'v47', title: 'Daily Office Clean Ste 200',scheduledStart: d(1),   status: 'scheduled',   client: { id: 'c25', name: 'Emerald Coast Offices' },  property: { street: '2100 N Palafox St Ste 200', city: 'Pensacola' },       vendor: V('vd05','Bay Clean Team') },
  { id: 'v48', title: 'Weekly Common Area Clean',  scheduledStart: d(3),   status: 'scheduled',   client: { id: 'c25', name: 'Emerald Coast Offices' },  property: { street: '800 W Garden St Ste 300',   city: 'Pensacola' },       vendor: V('vd05','Bay Clean Team') },
];
